name: aqaumatic_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+28
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.4.0 # or any other plugin
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  #badges: 2.0.2
  badges: ^3.1.2
  cached_network_image: ^3.4.0
  collection: ^1.19.1
  equatable: ^2.0.7
  file_picker: ^8.0.7
  flutter_animate: ^4.5.2
  flutter_cache_manager: ^3.4.1
  flutter_plugin_android_lifecycle:
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.8.0
  from_css_color: 2.0.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: 1.2.1
  infinite_scroll_pagination: ^4.0.0
  intl:
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider:
  path_provider_android:
  path_provider_foundation: ^2.4.1
  path_provider_platform_interface: 2.1.2
  photo_view: ^0.15.0
  plugin_platform_interface: 2.1.8
  pointer_interceptor: ^0.10.1+2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  shared_preferences_android: ^2.4.10
  shared_preferences_foundation: ^2.5.4
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  sqflite: ^2.4.2
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  url_launcher_android: ^6.3.16
  url_launcher_ios: ^6.3.3
  url_launcher_platform_interface: 2.3.2
  uuid: ^4.0.0
  webview_flutter: ^4.9.0
  webview_flutter_android: ^3.16.9
  webview_flutter_platform_interface: ^2.13.1
  webview_flutter_wkwebview: ^3.22.1
  webviewx_plus: ^0.5.1+1
  flutter_html:
  flutter_cached_pdfview: ^0.4.2
  flutter_launcher_icons: ^0.14.4
  in_app_update: ^4.2.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  pointer_interceptor: ^0.10.1+2
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_launcher_icons: 0.14.4
  flutter_lints: ^6.0.0
  image: ^4.5.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
